plugins {
	id 'net.fabricmc.fabric-loom' version "${loom_version}"
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	implementation "net.fabricmc:fabric-loader:${project.loader_version}"
	implementation fabricApi.module("fabric-events-interaction-v0", project.fabric_api_version)
	implementation fabricApi.module("fabric-lifecycle-events-v1", project.fabric_api_version)
}

processResources {
	def version = project.version
	def name = project.mod_name
	def id = project.mod_id
	inputs.property "version", version
	inputs.property "name", name
	inputs.property "id", id
	filteringCharset = "UTF-8"

	filesMatching("fabric.mod.json") {
		expand (
			"version": version,
			"name": name,
			"id": id
		)
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 25
	it.options.encoding = "UTF-8"
}

java {
	sourceCompatibility = JavaVersion.VERSION_25
	targetCompatibility = JavaVersion.VERSION_25
}
